package com.neo.dao;

import com.neo.entity.Consultation;
import java.util.List;

public interface ConsultationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consultation
     *
     * @mbg.generated Mon Apr 02 16:55:27 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consultation
     *
     * @mbg.generated Mon Apr 02 16:55:27 CST 2018
     */
    int insert(Consultation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consultation
     *
     * @mbg.generated Mon Apr 02 16:55:27 CST 2018
     */
    Consultation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consultation
     *
     * @mbg.generated Mon Apr 02 16:55:27 CST 2018
     */
    List<Consultation> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consultation
     *
     * @mbg.generated Mon Apr 02 16:55:27 CST 2018
     */
    int updateByPrimaryKey(Consultation record);
}